export const STORE_INFO = {
  name: 'Royale Sleepy',
  tagline: 'Sleep Better. Live Better.',
  address: 'Main Road, Berhampur, Odisha - 760001',
  phone: '+91 99999 99999',
  email: 'royalesleepy@gmail.com',
  whatsapp: '919999999999',
  instagram: 'https://instagram.com/royalesleepy',
  facebook: 'https://facebook.com/royalesleepy',
}

export const CATEGORIES = ['All', 'Orthopedic', 'Memory Foam', 'Spring', 'Latex', 'Luxury', 'Kids']

// Demo products (replaced by Firebase data in production)
export const DEMO_PRODUCTS = [
  {
    id: '1',
    name: 'Royal Comfort Elite',
    description: 'Experience unparalleled luxury with our flagship memory foam mattress, designed for royalty.',
    price: 28999,
    discount: 15,
    category: 'Memory Foam',
    sizes: ['Single', 'Double', 'Queen', 'King'],
    variants: ['Soft', 'Medium', 'Firm'],
    stock: true,
    featured: true,
    images: ['https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80'],
    createdAt: new Date(),
  },
  {
    id: '2',
    name: 'Orthopedic Supreme',
    description: 'Doctor-recommended orthopedic support for your spine and joints.',
    price: 22999,
    discount: 10,
    category: 'Orthopedic',
    sizes: ['Single', 'Double', 'Queen', 'King'],
    variants: ['Medium', 'Firm'],
    stock: true,
    featured: true,
    images: ['https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80'],
    createdAt: new Date(),
  },
  {
    id: '3',
    name: 'Latex Bliss',
    description: 'Natural latex for a breathable, hypoallergenic sleep experience.',
    price: 34999,
    discount: 5,
    category: 'Latex',
    sizes: ['Single', 'Double', 'Queen', 'King'],
    variants: ['Soft', 'Medium'],
    stock: true,
    featured: true,
    images: ['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&q=80'],
    createdAt: new Date(),
  },
  {
    id: '4',
    name: 'Pocket Spring Prestige',
    description: 'Individual pocket springs for motion isolation and targeted support.',
    price: 31999,
    discount: 20,
    category: 'Spring',
    sizes: ['Double', 'Queen', 'King'],
    variants: ['Medium', 'Firm'],
    stock: true,
    featured: false,
    images: ['https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80'],
    createdAt: new Date(),
  },
  {
    id: '5',
    name: 'Cloud Nine Kids',
    description: 'Specially designed for growing children with firm orthopedic support.',
    price: 12999,
    discount: 0,
    category: 'Kids',
    sizes: ['Single'],
    variants: ['Medium', 'Firm'],
    stock: true,
    featured: false,
    images: ['https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=800&q=80'],
    createdAt: new Date(),
  },
  {
    id: '6',
    name: 'Emperor\'s Luxury',
    description: 'Our most premium offering — handcrafted with natural cashmere and silk layers.',
    price: 64999,
    discount: 0,
    category: 'Luxury',
    sizes: ['Queen', 'King'],
    variants: ['Soft', 'Medium', 'Firm'],
    stock: true,
    featured: true,
    images: ['https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800&q=80'],
    createdAt: new Date(),
  },
]

export const DEMO_REVIEWS = [
  {
    id: '1',
    name: 'Priya Sharma',
    city: 'Berhampur',
    rating: 5,
    text: 'Best mattress I have ever owned! The Royal Comfort Elite completely transformed my sleep. Waking up refreshed every single morning.',
    avatar: 'PS',
  },
  {
    id: '2',
    name: 'Rajesh Kumar',
    city: 'Bhubaneswar',
    rating: 5,
    text: 'The Orthopedic Supreme fixed my back pain within weeks. Highly recommend Royale Sleepy for anyone with spine issues.',
    avatar: 'RK',
  },
  {
    id: '3',
    name: 'Ananya Das',
    city: 'Berhampur',
    rating: 5,
    text: 'Visited the showroom and was blown away by the quality. The staff is very helpful and the prices are very reasonable.',
    avatar: 'AD',
  },
  {
    id: '4',
    name: 'Suresh Patro',
    city: 'Cuttack',
    rating: 4,
    text: 'Great quality mattresses. The Latex Bliss is incredibly comfortable. Drove from Cuttack — absolutely worth the journey!',
    avatar: 'SP',
  },
  {
    id: '5',
    name: 'Meena Nayak',
    city: 'Berhampur',
    rating: 5,
    text: 'Bought the Emperor\'s Luxury for our new home. It is genuinely world-class quality. Royale Sleepy is a gem in Berhampur.',
    avatar: 'MN',
  },
]
